### PR TITLE
Gulpfile

### PR DESCRIPTION
**Pull request by sup**
(#1)

[Review on Reviewable](https://reviewable.io/reviews/pixeldesu/kado/2)

### CODE REVIEW

**Comment by pixeldesu** [comment]
<sup>**[Gulpfile.js, line 11 \[r1\]](https://reviewable.io:443/reviews/pixeldesu/kado/2#-K2hCrNfBlG1Nri6yS-m)** ([raw file](https://github.com/pixeldesu/kado/blob/eeb4855d5135ed5a3a70774b35988981d2a062a0/Gulpfile.js#L11)):</sup>
Actually, you will only need to compile a .scss file called `kado.scss` in `sass/`.

This file will imports files from each platform, which also just include their components from `components/`.


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/pixeldesu/kado/2)

**Comment by pixeldesu** [comment]
<sup>**[Gulpfile.js, line 26 \[r1\]](https://reviewable.io:443/reviews/pixeldesu/kado/2#-K2hDNWAOjDskdXhjWfH)** ([raw file](https://github.com/pixeldesu/kado/blob/eeb4855d5135ed5a3a70774b35988981d2a062a0/Gulpfile.js#L26)):</sup>
See above comment.


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/pixeldesu/kado/2)

**Comment by sup** [comment]
Review status: 0 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

<sup>**[Gulpfile.js, line 11 \[r1\]](https://reviewable.io:443/reviews/pixeldesu/kado/2#-K2hCrNfBlG1Nri6yS-m)** ([raw file](https://github.com/pixeldesu/kado/blob/eeb4855d5135ed5a3a70774b35988981d2a062a0/Gulpfile.js#L11)):</sup>
alright!


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/pixeldesu/kado/2)

**Comment by pixeldesu** [comment]
Besides the changes I marked for the Gulpfile, I'd also like you to squash commits, because this is an unnecessary high amount of commits, since you add and remove kss.

A detailed guide on how you can squash commits can be found here:
http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html


---







Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/pixeldesu/kado/2)

**Comment by sup** [comment]
Hmm, I'd have to do a force push for that to work. Is that okay?


---

Review status: 0 of 3 files reviewed at latest revision, all discussions resolved.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/pixeldesu/kado/2)

**Comment by pixeldesu** [comment]
I think so, as long as the commit number is decreased I'm fine with it. And a force push at the beginning of a repository shouldn't do too much damage.


---







Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/pixeldesu/kado/2)

**Comment by sup** [comment]
what

**Comment by sup** [comment]
might've accidentally squashed your commit too, i'll open a new pr

**Pull request closed without merging**
